import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase, supabaseConfigured } from './supabase';
import { Plus, Search, X, Tag, Clock3, CheckCircle2, Circle, Loader2, XCircle, BarChart3, ClipboardList, Trash2, MessageSquarePlus, ChevronLeft, Phone, MessageCircle, MapPin, Instagram, AlertTriangle, Settings, Download, Upload, Pencil, RotateCcw, Menu, LogOut, ShieldCheck, Users, UserPlus, Lock, Eye, EyeOff, ChevronDown } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import * as XLSX from 'xlsx';
import './styles.css';

const STATUSES=['Não iniciado','Em andamento','Concluído','Cancelado'];
const PRIORIDADES=['Baixa','Média','Alta','Urgente'];
const DEFAULT_CANAIS=['WhatsApp','Telefone','Rua','Instagram'];
const DEFAULT_CATEGORIAS=['Atendimento','Cadastro','Agendamento','Documento'];
const STATUS_META={
 'Não iniciado':{cls:'neutral',icon:Circle},'Em andamento':{cls:'info',icon:Loader2},'Concluído':{cls:'success',icon:CheckCircle2},'Cancelado':{cls:'danger',icon:XCircle}
};
const PRIORITY_META={'Baixa':'low','Média':'medium','Alta':'high','Urgente':'urgent'};
const CANAL_ICON={WhatsApp:MessageCircle,Telefone:Phone,Rua:MapPin,Instagram};
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
const isoNow=()=>new Date().toISOString();
const fmtDate=(v,time=false)=>{if(!v)return '—';const d=new Date(v.length===10?`${v}T00:00:00`:v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('pt-BR',time?{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit',year:'numeric'});};
const overdue=(v,s)=>{if(!v||s==='Concluído'||s==='Cancelado')return false;return new Date(`${v}T23:59:59`)<new Date();};

function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [loading,setLoading]=useState(true); const [authError,setAuthError]=useState('');
 useEffect(()=>{ if(!supabaseConfigured){setLoading(false);return;} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe(); },[]);
 useEffect(()=>{if(!session){setProfile(null);setLoading(false);return;} supabase.from('profiles').select('*').eq('id',session.user.id).single().then(({data})=>{setProfile(data);setLoading(false);});},[session]);
 if(loading)return <Splash/>;
 if(!supabaseConfigured)return <SetupScreen/>;
 if(!session)return <Login onError={setAuthError} error={authError}/>;
 return <Dashboard session={session} profile={profile}/>;
}
function Splash(){return <div className="splash"><div className="brandMark">GD</div><h1>Gestão de Demandas</h1><p>Preparando seu ambiente seguro…</p></div>}
function SetupScreen(){return <div className="authPage"><div className="authCard"><div className="brandMark">GD</div><h1>Gestão de Demandas</h1><p className="muted">O projeto está pronto para receber o banco seguro na nuvem.</p><div className="setupBox"><ShieldCheck size={22}/><div><strong>Configure o Supabase</strong><p>Copie <code>.env.example</code> para <code>.env.local</code> e informe a URL e a chave anon pública do seu projeto.</p></div></div><div className="steps"><span>1</span> Crie um projeto no Supabase<br/><span>2</span> Execute <code>supabase/schema.sql</code><br/><span>3</span> Preencha as variáveis de ambiente<br/><span>4</span> Rode <code>npm run dev</code></div></div></div>}
function Login({onError,error}){const [mode,setMode]=useState('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');const [show,setShow]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);onError('');setMsg('');try{if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}else{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset`});if(error)throw error;setMsg('Se o e-mail existir, enviaremos as instruções de recuperação.');}}catch(e){onError(e.message==='Invalid login credentials'?'E-mail ou senha incorretos.':e.message);}finally{setBusy(false)}}
 return <div className="authPage"><div className="authCard"><div className="authBrand"><div className="brandMark">GD</div><div><b>Gestão de Demandas</b><span>Ambiente interno</span></div></div><div className="authHeading"><h1>{mode==='login'?'Bem-vindo de volta':'Recuperar acesso'}</h1><p>{mode==='login'?'Entre para acessar as demandas da equipe.':'Informe seu e-mail para receber o link.'}</p></div><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="seu@email.com"/></label>{mode==='login'&&<label>Senha<div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>}{(error||msg)&&<div className={error?'formError':'formSuccess'}>{error||msg}</div>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar com segurança':'Enviar link'}</button></form><button className="textButton" onClick={()=>{setMode(mode==='login'?'reset':'login');onError('');setMsg('')}}>{mode==='login'?'Esqueci minha senha':'Voltar para o login'}</button><div className="securityNote"><Lock size={14}/> Seus dados são protegidos por autenticação e regras de acesso no banco.</div></div></div>}

function Dashboard({session,profile}){const [mobileMenu,setMobileMenu]=useState(false);const [tab,setTab]=useState('demandas');const [demands,setDemands]=useState([]);const [channels,setChannels]=useState(DEFAULT_CANAIS);const [categories,setCategories]=useState(DEFAULT_CATEGORIAS);const [selected,setSelected]=useState(null);const [formOpen,setFormOpen]=useState(false);const [editing,setEditing]=useState(null);const [toast,setToast]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const role=profile?.role||'member';
 const load=async()=>{setLoading(true);setError('');const [d,c,k]=await Promise.all([supabase.from('demandas').select('*').order('created_at',{ascending:false}),supabase.from('settings').select('key,value').in('key',['canais','categorias'])]);if(d.error) setError(d.error.message); else setDemands(d.data||[]);const map=Object.fromEntries((k.data||[]).map(x=>[x.key,x.value]));setChannels(Array.isArray(map.canais)&&map.canais.length?map.canais:DEFAULT_CANAIS);setCategories(Array.isArray(map.categorias)&&map.categorias.length?map.categorias:DEFAULT_CATEGORIAS);setLoading(false);};
 useEffect(()=>{load();},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)}},[toast]);
 async function add(form){const {data,error}=await supabase.from('demandas').insert({...form,created_by:session.user.id}).select().single();if(error){setToast('Não foi possível criar a demanda.');return;}setDemands(p=>[data,...p]);setFormOpen(false);setToast('Demanda criada com sucesso.');}
 async function update(id,changes){const {data,error}=await supabase.from('demandas').update(changes).eq('id',id).select().single();if(error){setToast('Não foi possível atualizar.');return;}setDemands(p=>p.map(x=>x.id===id?data:x));setSelected(data);setToast('Demanda atualizada.');}
 async function remove(id){if(role!=='admin')return; if(!confirm('Excluir esta demanda permanentemente?'))return;const {error}=await supabase.from('demandas').delete().eq('id',id);if(error){setToast('Exclusão bloqueada.');return;}setDemands(p=>p.filter(x=>x.id!==id));setSelected(null);setToast('Demanda excluída.');}
 async function logout(){await supabase.auth.signOut();}
 return <div className="appShell"><aside className={`sidebar ${mobileMenu?'open':''}`}><div className="sideBrand"><div className="brandMark small">GD</div><div><b>Gestão</b><span>Demandas</span></div></div><nav><NavItem active={tab==='demandas'} icon={ClipboardList} label="Demandas" onClick={()=>{setTab('demandas');setSelected(null);setMobileMenu(false)}}/><NavItem active={tab==='relatorios'} icon={BarChart3} label="Relatórios" onClick={()=>{setTab('relatorios');setSelected(null);setMobileMenu(false)}}/>{role==='admin'&&<NavItem active={tab==='equipe'} icon={Users} label="Equipe" onClick={()=>{setTab('equipe');setSelected(null);setMobileMenu(false)}}/>}<NavItem active={tab==='config'} icon={Settings} label="Configurações" onClick={()=>{setTab('config');setSelected(null);setMobileMenu(false)}}/></nav><div className="sideBottom"><div className="profileMini"><div className="avatar">{(profile?.full_name||session.user.email).slice(0,1).toUpperCase()}</div><div><b>{profile?.full_name||'Usuário'}</b><span>{role==='admin'?'Administrador':'Equipe'}</span></div></div><button className="logout" onClick={logout}><LogOut size={16}/> Sair</button></div></aside><main className="main"><header className="topbar"><button className="mobileMenu" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button><div><p className="eyebrow">PAINEL INTERNO</p><h1>{selected?'Detalhes da demanda':tab==='demandas'?'Demandas':tab==='relatorios'?'Relatórios':tab==='equipe'?'Equipe':'Configurações'}</h1></div><div className="topActions"><div className="avatar">{(profile?.full_name||session.user.email).slice(0,1).toUpperCase()}</div></div></header>{error&&<div className="alert danger"><AlertTriangle size={17}/>{error}</div>}{toast&&<div className="toast">{toast}</div>}{loading?<div className="loading"><Loader2 className="spin"/> Carregando dados…</div>:selected?<Detail demand={selected} role={role} onBack={()=>setSelected(null)} onUpdate={update} onDelete={()=>remove(selected.id)} onEdit={()=>{setEditing(selected);setFormOpen(true)}}/>:tab==='demandas'?<Demandas demands={demands} channels={channels} categories={categories} onSelect={setSelected} onNew={()=>{setEditing(null);setFormOpen(true)}}/>:tab==='relatorios'?<Reports demands={demands}/>:tab==='equipe'?<Team/>:<SettingsView channels={channels} categories={categories} role={role} onReload={load}/>} {formOpen&&<DemandModal demand={editing} channels={channels} categories={categories} onClose={()=>{setFormOpen(false);setEditing(null)}} onSave={editing?f=>{update(editing.id,f);setFormOpen(false);setEditing(null)}:add}/></main></div>}
function NavItem({active,icon:Icon,label,onClick}){return <button className={`navItem ${active?'active':''}`} onClick={onClick}><Icon size={18}/>{label}</button>}

function Demandas({demands,channels,categories,onSelect,onNew}){const [q,setQ]=useState('');const [status,setStatus]=useState('Todos');const [channel,setChannel]=useState('Todos');const [category,setCategory]=useState('Todos');const [priority,setPriority]=useState('Todos');const [deadline,setDeadline]=useState('Todos');const filtered=useMemo(()=>demands.filter(d=>(!q||[d.demanda,d.solicitante,d.contato,d.canal,d.categoria].some(x=>String(x||'').toLowerCase().includes(q.toLowerCase())))&&(status==='Todos'||d.status===status)&&(channel==='Todos'||d.canal===channel)&&(category==='Todos'||d.categoria===category)&&(priority==='Todos'||d.prioridade===priority)&&(deadline==='Todos'||(deadline==='Atrasadas'?overdue(d.prazo,d.status):deadline==='Sem prazo'?!d.prazo:!!d.prazo))),[demands,q,status,channel,category,priority,deadline]);const clear=()=>{setQ('');setStatus('Todos');setChannel('Todos');setCategory('Todos');setPriority('Todos');setDeadline('Todos')};
 return <section className="content"><div className="hero"><div><h2>Central de atendimentos</h2><p>Registre, acompanhe e organize todas as solicitações da equipe.</p></div><div className="heroActions"><button className="secondary" onClick={()=>exportXlsx(demands)}><Download size={15}/> Exportar</button><button className="primary" onClick={onNew}><Plus size={17}/> Nova demanda</button></div></div><div className="metrics"><Metric label="Total" value={demands.length}/><Metric label="Em andamento" value={demands.filter(x=>x.status==='Em andamento').length}/><Metric label="Urgentes" value={demands.filter(x=>x.prioridade==='Urgente'&&x.status!=='Concluído').length}/><Metric label="Atrasadas" value={demands.filter(x=>overdue(x.prazo,x.status)).length}/></div><div className="filterPanel"><div className="search"><Search size={17}/><input placeholder="Buscar demanda, pessoa ou contato…" value={q} onChange={e=>setQ(e.target.value)}/></div><Select value={status} onChange={setStatus} options={['Todos',...STATUSES]} label="Status"/><Select value={channel} onChange={setChannel} options={['Todos',...channels]} label="Canal"/><Select value={category} onChange={setCategory} options={['Todos',...categories]} label="Categoria"/><Select value={priority} onChange={setPriority} options={['Todos',...PRIORIDADES]} label="Prioridade"/><Select value={deadline} onChange={setDeadline} options={['Todos','Atrasadas','Com prazo','Sem prazo']} label="Prazo"/></div><div className="listHeader"><span>{filtered.length} demanda{filtered.length===1?'':'s'}</span>{(q||status!=='Todos'||channel!=='Todos'||category!=='Todos'||priority!=='Todos'||deadline!=='Todos')&&<button className="textButton inline" onClick={clear}><RotateCcw size={14}/> Limpar filtros</button>}</div><div className="demandList">{filtered.length?filtered.map(d=><DemandCard key={d.id} d={d} onClick={()=>onSelect(d)}/>):<Empty/>}</div></section>}
function exportXlsx(rows){const data=rows.map(d=>({ID:d.id,Demanda:d.demanda||'',Solicitante:d.solicitante||'',Contato:d.contato||'',Canal:d.canal||'',Categoria:d.categoria||'',Prioridade:d.prioridade||'',Prazo:d.prazo||'',Status:d.status||'',Criada:fmtDate(d.created_at,true),Atualizada:fmtDate(d.updated_at,true)}));const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Demandas');XLSX.writeFile(wb,`demandas_${new Date().toISOString().slice(0,10)}.xlsx`)}

function DemandCard({d,onClick}){const sm=STATUS_META[d.status]||STATUS_META['Não iniciado'];const Icon=sm.icon;const Channel=CANAL_ICON[d.canal]||Tag;return <button className={`demandCard ${overdue(d.prazo,d.status)?'overdue':''}`} onClick={onClick}><div className="cardMain"><div><div className="cardTitle">{d.demanda}</div><div className="cardPerson">{d.solicitante||'Solicitante não informado'}</div></div><span className={`badge ${sm.cls}`}><Icon size={12}/>{d.status}</span></div><div className="cardMeta"><span><Channel size={13}/>{d.canal||'—'}</span><span><Tag size={13}/>{d.categoria||'—'}</span><span><Clock3 size={13}/>{d.prazo?fmtDate(d.prazo):'Sem prazo'}</span><span className={`priority ${PRIORITY_META[d.prioridade]||'medium'}`}>{d.prioridade||'Média'}</span></div></button>}
function Empty(){return <div className="empty"><ClipboardList size={28}/><h3>Nenhuma demanda encontrada</h3><p>Ajuste os filtros ou cadastre uma nova demanda.</p></div>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Select({value,onChange,options,label}){return <div className="select"><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{label}: {x}</option>)}</select><ChevronDown size={14}/></div>}

function Detail({demand:d,role,onBack,onUpdate,onDelete,onEdit}){const [note,setNote]=useState('');const sm=STATUS_META[d.status]||STATUS_META['Não iniciado'];const Icon=sm.icon;async function addNote(){if(!note.trim())return;await onUpdate(d.id,{last_note:note.trim()});setNote('')}
 return <section className="content detail"><button className="back" onClick={onBack}><ChevronLeft size={17}/> Voltar para demandas</button><div className="detailTop"><div><div className="eyebrow">DEMANDA</div><h2>{d.demanda}</h2><p>{d.solicitante||'Solicitante não informado'}</p></div><div className="detailActions"><button className="secondary" onClick={onEdit}><Pencil size={15}/> Editar</button>{role==='admin'&&<button className="dangerBtn" onClick={onDelete}><Trash2 size={15}/></button>}</div></div><div className="detailGrid"><div className="detailCard"><h3>Informações</h3><Info label="Solicitante" value={d.solicitante}/><Info label="Contato" value={d.contato}/><Info label="Canal" value={d.canal}/><Info label="Categoria" value={d.categoria}/><Info label="Prazo" value={d.prazo?fmtDate(d.prazo):'Sem prazo'}/><Info label="Criada em" value={fmtDate(d.created_at,true)}/></div><div className="detailCard"><h3>Status e prioridade</h3><div className="statusGrid">{STATUSES.map(s=><button key={s} className={`statusChoice ${s===d.status?'selected':''}`} onClick={()=>onUpdate(d.id,{status:s})}>{s===d.status&&<CheckCircle2 size={14}/>} {s}</button>)}</div><div className="priorityBlock"><span className="label">Prioridade</span><div className="priorityChoices">{PRIORIDADES.map(p=><button key={p} className={`priorityChoice ${PRIORITY_META[p]} ${p===d.prioridade?'selected':''}`} onClick={()=>onUpdate(d.id,{prioridade:p})}>{p}</button>)}</div></div></div></div><div className="detailCard"><h3>Observações</h3><div className="noteRow"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Adicionar uma observação…"/><button className="primary" onClick={addNote}><MessageSquarePlus size={16}/> Adicionar</button></div>{d.last_note&&<div className="noteItem"><b>Última observação</b><p>{d.last_note}</p></div>}</div></section>}
function Info({label,value}){return <div className="info"><span>{label}</span><strong>{value||'—'}</strong></div>}

function DemandModal({demand,channels,categories,onClose,onSave}){const [form,setForm]=useState({demanda:demand?.demanda||'',solicitante:demand?.solicitante||'',contato:demand?.contato||'',canal:demand?.canal||channels[0]||'',categoria:demand?.categoria||categories[0]||'',prioridade:demand?.prioridade||'Média',prazo:demand?.prazo||'',status:demand?.status||'Não iniciado'});const set=(k,v)=>setForm(p=>({...p,[k]:v}));return <Modal title={demand?'Editar demanda':'Nova demanda'} onClose={onClose}><form className="form" onSubmit={e=>{e.preventDefault();if(!form.demanda.trim())return;onSave(form)}}><label>Demanda<input autoFocus value={form.demanda} onChange={e=>set('demanda',e.target.value)} required placeholder="Descreva a solicitação"/></label><div className="two"><label>Solicitante<input value={form.solicitante} onChange={e=>set('solicitante',e.target.value)} placeholder="Nome completo"/></label><label>Contato<input value={form.contato} onChange={e=>set('contato',e.target.value)} placeholder="Telefone / WhatsApp"/></label></div><div className="two"><label>Canal<Select value={form.canal} onChange={v=>set('canal',v)} options={channels} label="Canal"/></label><label>Categoria<Select value={form.categoria} onChange={v=>set('categoria',v)} options={categories} label="Categoria"/></label></div><div className="two"><label>Prioridade<Select value={form.prioridade} onChange={v=>set('prioridade',v)} options={PRIORIDADES} label="Prioridade"/></label><label>Prazo<input type="date" value={form.prazo} onChange={e=>set('prazo',e.target.value)}/></label></div>{demand&&<label>Status<Select value={form.status} onChange={v=>set('status',v)} options={STATUSES} label="Status"/></label>}<div className="modalActions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" type="submit">{demand?'Salvar alterações':'Criar demanda'}</button></div></form></Modal>}
function Modal({title,onClose,children}){return <div className="modalOverlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modalHead"><div><h2>{title}</h2></div><button className="iconBtn" onClick={onClose}><X/></button></div>{children}</div></div>}

function Reports({demands}){const byStatus=STATUSES.map(s=>({name:s,total:demands.filter(d=>d.status===s).length}));const byCategory=[...new Set(demands.map(d=>d.categoria).filter(Boolean))].map(c=>({name:c,total:demands.filter(d=>d.categoria===c).length}));return <section className="content"><div className="hero"><div><h2>Visão geral</h2><p>Acompanhe o volume e a situação das demandas.</p></div></div><div className="metrics"><Metric label="Total" value={demands.length}/><Metric label="Concluídas" value={demands.filter(d=>d.status==='Concluído').length}/><Metric label="Urgentes" value={demands.filter(d=>d.prioridade==='Urgente').length}/><Metric label="Atrasadas" value={demands.filter(d=>overdue(d.prazo,d.status)).length}/></div><div className="charts"><div className="chartCard"><h3>Por status</h3><div className="chart"><ResponsiveContainer width="100%" height={270}><BarChart data={byStatus}><CartesianGrid vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="total" fill="#0f4c4a" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="chartCard"><h3>Por categoria</h3><div className="chart"><ResponsiveContainer width="100%" height={270}><BarChart data={byCategory} layout="vertical"><CartesianGrid horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={100} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="total" fill="#2c7774" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></div></div></section>}
function Team(){const [users,setUsers]=useState([]);useEffect(()=>{supabase.from('profiles').select('id,full_name,role,created_at').order('created_at').then(({data})=>setUsers(data||[]))},[]);return <section className="content"><div className="hero"><div><h2>Equipe</h2><p>Contas autorizadas a acessar o sistema.</p></div></div><div className="teamList">{users.map(u=><div className="teamRow" key={u.id}><div className="avatar">{(u.full_name||'U').slice(0,1).toUpperCase()}</div><div><b>{u.full_name||'Sem nome'}</b><span>{u.role==='admin'?'Administrador':'Equipe'}</span></div><span className="roleBadge">{u.role}</span></div>)}</div></section>}
function SettingsView({channels,categories,role,onReload}){const [busy,setBusy]=useState(false);async function save(key,value){if(role!=='admin')return;setBusy(true);await supabase.from('settings').upsert({key,value,updated_at:isoNow()});setBusy(false);onReload()}return <section className="content"><div className="hero"><div><h2>Configurações</h2><p>Opções usadas no cadastro de demandas.</p></div></div>{role!=='admin'?<div className="empty"><ShieldCheck size={28}/><h3>Acesso restrito</h3><p>Somente administradores podem alterar configurações.</p></div>:<div className="settingsGrid"><SettingList title="Canais" items={channels} onSave={v=>save('canais',v)} busy={busy}/><SettingList title="Categorias" items={categories} onSave={v=>save('categorias',v)} busy={busy}/></div>}</section>}
function SettingList({title,items,onSave,busy}){const [list,setList]=useState(items);const [value,setValue]=useState('');useEffect(()=>setList(items),[items]);return <div className="settingCard"><h3>{title}</h3><div className="chips">{list.map(x=><span className="chip" key={x}>{x}<button onClick={()=>setList(list.filter(y=>y!==x))}>×</button></span>)}</div><div className="addRow"><input value={value} onChange={e=>setValue(e.target.value)} placeholder={`Adicionar ${title.toLowerCase().slice(0,-1)}…`}/><button className="secondary" onClick={()=>{if(value.trim()){setList([...list,value.trim()]);setValue('')}}}><Plus size={15}/></button></div><button className="primary" disabled={busy} onClick={()=>onSave(list)}>Salvar {title.toLowerCase()}</button></div>}

function ExportButton({demands}){return null}
function InfoFooter(){return null}

createRoot(document.getElementById('root')).render(<App/>);
